apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-config0001
data:
  exporter_config: |
    modules:
      http_2xx:
        prober: http
        http:
          preferred_ip_protocol: "ip4"
          ip_protocol_fallback: false
          tls_config:
            insecure_skip_verify: true
      http_post_2xx:
        prober: http
        http:
          method: POST
          preferred_ip_protocol: "ip4"
          ip_protocol_fallback: false
          tls_config:
            insecure_skip_verify: true
      tcp_connect:
        prober: tcp
        tcp:
          preferred_ip_protocol: "ip4"
          ip_protocol_fallback: false
          tls_config:
            insecure_skip_verify: true
      pop3s_banner:
        prober: tcp
        tcp:
          query_response:
          - expect: "^+OK"
          preferred_ip_protocol: "ip4"
          ip_protocol_fallback: false
          tls: true
          tls_config:
            insecure_skip_verify: true
      ssh_banner:
        prober: tcp
        tcp:
          query_response:
          - expect: "^SSH-2.0-"
          preferred_ip_protocol: "ip4"
          ip_protocol_fallback: false
          tls_config:
            insecure_skip_verify: true
      irc_banner:
        prober: tcp
        tcp:
          query_response:
          - send: "NICK prober"
          - send: "USER prober prober prober :prober"
          - expect: "PING :([^ ]+)"
            send: "PONG ${1}"
          - expect: "^:[^ ]+ 001"
          preferred_ip_protocol: "ip4"
          ip_protocol_fallback: false
          tls_config:
            insecure_skip_verify: true
      icmp:
        prober: icmp
        icmp:
          preferred_ip_protocol: "ip4"
          ip_protocol_fallback: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-deployment0001
spec:
  selector:
    matchLabels:
      app: blackbox
      instance: blackbox0001
  replicas: 1
  template:
    metadata:
      labels:
        app: blackbox
        instance: blackbox0001
    spec:
      # root access is needed for icmp module
      # securityContext should not be defined or
      # defined as root
      # securityContext:
      #   runAsNonRoot: false
      #   runAsUser: 0
      #   fsGroup: 0
      containers:
      - name: blackbox-exporter
        image: prom/blackbox-exporter
        args:
          - "--config.file=/config/blackbox.yml"
        ports:
          - containerPort: 9115
            name: http
        readinessProbe:
          httpGet:
            path: /health
            port: http
        livenessProbe:
          httpGet:
            path: /health
            port: http
        volumeMounts:
          - name: config
            mountPath: /config
      volumes:
        - name: config
          configMap:
            name: blackbox-config0001
            items:
              - key: exporter_config
                path: blackbox.yml

---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-svc0001
spec:
  selector:
    app: blackbox
    instance: blackbox0001
  type: NodePort
  ports:
    - port: 9115
      targetPort: 9115
      # nodePort: 39115
