apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc0001
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment0001
spec:
  selector:
    matchLabels:
      app: grafana
      instance: grafana0001
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
        instance: grafana0001
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
          - containerPort: 3000
        volumeMounts:
          - name: data
            mountPath: /var/lib/grafana
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: grafana-pvc0001

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc0001
spec:
  selector:
    app: grafana
    instance: grafana0001
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      # nodePort: 39090
