apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway-deployment0001
spec:
  selector:
    matchLabels:
      app: pushgateway
      instance: pushgateway0001
  replicas: 1
  template:
    metadata:
      labels:
        app: pushgateway
        instance: pushgateway0001
    spec:
      containers:
      - name: pushgateway
        image: prom/pushgateway
        ports:
          - containerPort: 9091
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9091
          initialDelaySeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9091
          initialDelaySeconds: 10
          timeoutSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway-svc0001
spec:
  selector:
    app: pushgateway
    instance: pushgateway0001
  type: NodePort
  ports:
    - port: 9091
      targetPort: 9091
      # nodePort: 39091
