---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sflow-rt-deployment0001
spec:
  selector:
    matchLabels:
      app: sflow-rt
      instance: sflow-rt0001
  replicas: 1
  template:
    metadata:
      labels:
        app: sflow-rt
        instance: sflow-rt0001
    spec:
      containers:
      - name: sflow-rt
        image: sflow/prometheus
        args:
          - "-Dsnmp.ifname=yes"
        ports:
          - containerPort: 8008
            name: http
          - containerPort: 6343
            name: sflow
            protocol: UDP

---
apiVersion: v1
kind: Service
metadata:
  name: sflow-rt-svc0001
spec:
  selector:
    app: sflow-rt
    instance: sflow-rt0001
  type: NodePort
  ports:
    - port: 80
      targetPort: 8008
      name: http
    - port: 6343
      targetPort: 6343
      protocol: UDP
      name: sflow
