# Values for influxdata/telegraf
service:
  type: NodePort

config:
  outputs:
    - prometheus_client:
        listen: ":9273"
        metric_version: 2
  inputs:
    - sqlserver:
        servers:
        - "Server=192.168.10.10;Port=1433;User Id=telegraf;Password=password;app name=telegraf;log=1;"
        query_version: 2
        exclude_query:
          - "Schedulers"
          - "SqlRequests"
