# Values for stable/grafana
service:
  type: NodePort

persistence:
  enabled: true
  storageClassName: longhorn
  size: 12Gi

adminUser: admin
adminPassword: admin

admin: {}

plugins:
  - jdbranham-diagram-panel
