# The frequently used Kind configuration to provision a POC Kubernetes cluster
# Refer to https://kind.sigs.k8s.io/docs/user/configuration/
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # Since pods run from the containerized nodes, they cannot be accessed from
  # the host (the server which runs "kind create ..."). To expose pods (services),
  # explicit NodePort values need to be specified on below defined ports which
  # have been mapped to the host.
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP
  - containerPort: 30080
    hostPort: 30080
    protocol: UDP
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "role=controller"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "role=worker"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "role=worker"
