apiVersion: v1
kind: Secret
metadata:
  name: gluster-secret
  namespace: default
type: "kubernetes.io/glusterfs"
data:
  # echo -n "password" | base64
  key: cGFzc3dvcmQ=

---
 apiVersion: storage.k8s.io/v1
 kind: StorageClass
 metadata:
   name: gluster
 provisioner: kubernetes.io/glusterfs
 reclaimPolicy: Delete
 volumeBindingMode: Immediate
 parameters:
   resturl: "http://192.168.56.181:8080"
   clusterid: "6588195dfdc9089546d9c45ff59e2273"
   restauthenabled: "true"
   restuser: "admin"
   secretName: "gluster-secret"
   secretNamespace: "default"
   volumetype: "replicate:3"
   volumenameprefix: "k8s"
