---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2
spec:
  selector:
    matchLabels:
      app: apache2
  replicas: 3
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: www
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: apache2
