apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc0001
spec:
  storageClassName: powerstore
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: powerstore-pod0001
  labels:
    name: powerstore-pod0001
spec:
  containers:
  - name: powerstore-pod0001
    image: busybox
    command: ["sleep", "60000"]
    volumeMounts:
    - name: vol0001
      mountPath: /usr/share/busybox
      readOnly: false
  volumes:
  - name: vol0001
    persistentVolumeClaim:
      claimName: pvc0001
