apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
      tier: frontend
  template:
    metadata:
      labels:
        app: tomcat
        tier: frontend
    spec:
      containers:
        - name: tomcat
          image: tomcat
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30001
  selector:
    app: tomcat
    tier: frontend
