# Apply to namespace
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range1
spec:
  limits:
  - default:
      cpu: 1
      memory: 512Mi
    defaultRequest:
      cpu: 0.5
      memory: 256Mi
    min:
      cpu: 0.25
      memory: 128Mi
    max:
      cpu: 2
      memory: 1Gi
    type: Container

