# Apply to namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ns-quota1
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pod-num-quota1
spec:
  hard:
    pods: "2"
