# Define a service account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tester2
  namespace: default

# Define a role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role1
  namespace: default
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

# Assign permissions by using role binding
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role1
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role1
subjects:
- namespace: default
  kind: ServiceAccount
  name: tester2
