apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
# secret data as base64 encoded strings
# encode: echo -n "original string" | base64
# decode: echo -n "encoded string" | base64 --decode
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=
# secret data as unencoded strings, kubernets will encode it automatically
# if a filed is specified with both data and stringData, stringData works
stringData:
  port: "8080"

---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    env:
      # Use secrets as environment variables
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
      - name: SECRET_PORT
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: port
    volumeMounts:
      # secretes will be presented as individual files under the mountPath
      # E.g., in this example, files username, password, and port will be
      # accessible from /etc/mysecret/username|password|port and the contents
      # are will the decoded values
      - name: mysecretvol1
        mountPath: /etc/mysecret
      # the key username will be presented as file /opt/mysecret/group1/username
      # other keys won't be presented under the directory
      - name: mysecretvol2
        mountPath: /opt/mysecret
  volumes:
    - name: mysecretvol1
      secret:
        secretName: mysecret
    # Projection: only keys specified will be projected,
    # other keys won't be used
    - name: mysecretvol2
      secret:
        secretName: mysecret
        items:
          - key: username
            path: group1/username
