apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  containers:
  - name: tomcat
    image: tomcat
    ports:
      - containerPort: 8080
    volumeMounts:
      - name: logs
        mountPath: /usr/local/tomcat/logs
  - name: busybox
    image: busybox
    command: ["sh", "-c", "tail -f /logs/catalina*.log"]
    volumeMounts:
      - name: logs
        mountPath: /logs
  volumes:
    - name: logs
      emptyDir: {}
